/*============================================================================
	File:		0901 - View for Page Split Analysis.sql

	Summary:	This script extracts the page splits out of the Extended Event
				file which is generated by the script:
				0003 - XEvent for high transactional processes!

				THIS SCRIPT IS PART OF THE TRACK:
				"Database Partitioning"

	Date:		December 2020

	SQL Server Version: 2012 / 2014 / 2016 / 2017 / 2019
------------------------------------------------------------------------------
	Written by Uwe Ricken, db Berater GmbH

	This script is intended only as a supplement to demos and lectures
	given by Uwe Ricken.  
  
	THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF 
	ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED 
	TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
	PARTICULAR PURPOSE.
============================================================================*/
DROP TABLE IF EXISTS #EventData
GO

SELECT	CAST(event_Data AS xml) AS StatementData
INTO	#EventData
FROM	sys.fn_xe_file_target_read_file
		('T:\TraceFiles\0110*.xel', NULL, NULL, NULL);
GO

WITH XE
AS
(
	SELECT	StatementData.value('(event/@timestamp)[1]','datetime')								AS	[time],
			StatementData.value('(event/@name)[1]', 'VARCHAR(128)')								AS	[Event_name],
			StatementData.value('(event/data[@name="file_id"]/value)[1]','int')					AS	[file_id],
			StatementData.value('(event/data[@name="page_id"]/value)[1]','int')					AS	[page_id],
			StatementData.value('(event/data[@name="new_page_page_id"]/value)[1]','int')		AS	[new_page_id],
			StatementData.value('(event/data[@name="database_id"]/value)[1]','int')				AS	[database_id],
			StatementData.value('(event/data[@name="splitOperation"]/text)[1]','varchar(128)')	AS	[split_operation]
	FROM	#EventData
)
SELECT	DISTINCT
		XE.Event_name,
        XE.split_operation,
        XE.page_id,
        XE.new_page_id,
		XE.new_page_id - XE.page_id	AS	split_jump
FROM	XE
WHERE	(XE.new_page_id - XE.page_id) > 1
		AND XE.split_operation = 'SPLIT_FOR_INSERT'
GO